name: 1. Build and push docker images

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: The environment to deploy
        default: dev
        options:
          - dev
          - preprod
          - prod

env:
  DOCKER_REGISTRY: rbbbucym.gra7.container-registry.ovh.net
  APP_NAME: hive-login

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set APP_REPOSITORY
        run: echo "APP_REPOSITORY=hive-login-${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: 'image=moby/buildkit:v0.21.0'

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Install dependencies
        run: pnpm install

      - name: Generate stubs
        run: pnpm generate

      - name: Build for Docker
        run: pnpm build:docker

      - name: Build and Push Image
        id: build
        uses: docker/build-push-action@v5
        timeout-minutes: 10
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}/${{ env.APP_REPOSITORY }}:${{ github.event.inputs.environment }}
          push: true